### ISSUE TITLE
Support for Async controller methods

### ISSUE THREAD

**Issue by khorvat** [ploeh/Hyprlinkr#20]
Hi,

  do you plan to add support for async controllers ?

btw great library.

Thanks

**Comment by barbosatek** [comment]
AsyncController is MVC specific, do you have any workaround for WebAPI?

**Comment by khorvat** [comment]
Hi @barbosatek, the above example is working in WebAPI so could you give us an example if the issue you have ?

**Comment by ploeh** [comment]
> AsyncController is MVC specific, do you have any workaround for WebAPI?

Discussion moved to #42
