### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by VladislavAntonyuk** [ploeh/Hyprlinkr#47]

**Comment by ploeh** [comment]
I'm not sure I understand the question... What would you like to do?

**Comment by VladislavAntonyuk** [comment]
I have a UploadFile method in controller (api/{folderId}/upload)
I have another controller and method (api/folder/{folderId}/files/upload
I want to redirect link. So I use 
```
var uri = _linkBuilder.GetLink<FolderContentController>(c => c.UploadFile());
return Redirect(uri);
```

For get request this code works, but for POST I receive an error, that form data is not posted. Do you have a workaround? I found this gist https://gist.github.com/priore/7163408, but I don't want to use forms

**Comment by ploeh** [comment]
I'm sorry, but it's still not clear to me what the problem is. How do I reproduce it?

**Comment by VladislavAntonyuk** [comment]
how to redirect url api/{folderid}/upload to api/folder/{folderId}/files/upload
where it is a POST request

**Comment by ploeh** [comment]
Since I don't have your code, I don't know which Controller method would give you the URL `api/folder/{folderId}/files/upload`, so I don't see how I can answer that question with the information available to me.

**Comment by VladislavAntonyuk** [comment]
Sorry, I thought the utility performs redirect. it is only for get link
